server:
  port: 9001
spring:
  application:
    name: nacos-microservice-dept-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#消费者将要去访问的微服务名称
server-url:
  nacos-dept-service: http://nacos-microservice-dept-provider